# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=opengldebug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),opengldebug_x86)
  GLFW_config = opengldebug_x86
  Glad_config = opengldebug_x86
  qgfx_config = opengldebug_x86
  qgfx_test_config = opengldebug_x86
endif
ifeq ($(config),opengldebug_x64)
  GLFW_config = opengldebug_x64
  Glad_config = opengldebug_x64
  qgfx_config = opengldebug_x64
  qgfx_test_config = opengldebug_x64
endif
ifeq ($(config),openglrelease_x86)
  GLFW_config = openglrelease_x86
  Glad_config = openglrelease_x86
  qgfx_config = openglrelease_x86
  qgfx_test_config = openglrelease_x86
endif
ifeq ($(config),openglrelease_x64)
  GLFW_config = openglrelease_x64
  Glad_config = openglrelease_x64
  qgfx_config = openglrelease_x64
  qgfx_test_config = openglrelease_x64
endif
ifeq ($(config),opengldistribution_x86)
  GLFW_config = opengldistribution_x86
  Glad_config = opengldistribution_x86
  qgfx_config = opengldistribution_x86
  qgfx_test_config = opengldistribution_x86
endif
ifeq ($(config),opengldistribution_x64)
  GLFW_config = opengldistribution_x64
  Glad_config = opengldistribution_x64
  qgfx_config = opengldistribution_x64
  qgfx_test_config = opengldistribution_x64
endif
ifeq ($(config),vulkandebug_x86)
  GLFW_config = vulkandebug_x86
  Glad_config = vulkandebug_x86
  qgfx_config = vulkandebug_x86
  qgfx_test_config = vulkandebug_x86
endif
ifeq ($(config),vulkandebug_x64)
  GLFW_config = vulkandebug_x64
  Glad_config = vulkandebug_x64
  qgfx_config = vulkandebug_x64
  qgfx_test_config = vulkandebug_x64
endif
ifeq ($(config),vulkanrelease_x86)
  GLFW_config = vulkanrelease_x86
  Glad_config = vulkanrelease_x86
  qgfx_config = vulkanrelease_x86
  qgfx_test_config = vulkanrelease_x86
endif
ifeq ($(config),vulkanrelease_x64)
  GLFW_config = vulkanrelease_x64
  Glad_config = vulkanrelease_x64
  qgfx_config = vulkanrelease_x64
  qgfx_test_config = vulkanrelease_x64
endif
ifeq ($(config),vulkandistribution_x86)
  GLFW_config = vulkandistribution_x86
  Glad_config = vulkandistribution_x86
  qgfx_config = vulkandistribution_x86
  qgfx_test_config = vulkandistribution_x86
endif
ifeq ($(config),vulkandistribution_x64)
  GLFW_config = vulkandistribution_x64
  Glad_config = vulkandistribution_x64
  qgfx_config = vulkandistribution_x64
  qgfx_test_config = vulkandistribution_x64
endif

PROJECTS := GLFW Glad qgfx qgfx-test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/Glad -f Makefile config=$(Glad_config)
endif

qgfx: GLFW Glad
ifneq (,$(qgfx_config))
	@echo "==== Building qgfx ($(qgfx_config)) ===="
	@${MAKE} --no-print-directory -C projects/qgfx -f Makefile config=$(qgfx_config)
endif

qgfx-test: qgfx GLFW Glad
ifneq (,$(qgfx_test_config))
	@echo "==== Building qgfx-test ($(qgfx_test_config)) ===="
	@${MAKE} --no-print-directory -C projects/qgfx-test -f Makefile config=$(qgfx_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C dependencies/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C dependencies/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C projects/qgfx -f Makefile clean
	@${MAKE} --no-print-directory -C projects/qgfx-test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  opengldebug_x86"
	@echo "  opengldebug_x64"
	@echo "  openglrelease_x86"
	@echo "  openglrelease_x64"
	@echo "  opengldistribution_x86"
	@echo "  opengldistribution_x64"
	@echo "  vulkandebug_x86"
	@echo "  vulkandebug_x64"
	@echo "  vulkanrelease_x86"
	@echo "  vulkanrelease_x64"
	@echo "  vulkandistribution_x86"
	@echo "  vulkandistribution_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   qgfx"
	@echo "   qgfx-test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"